# Generated by Django 3.2.2 on 2021-05-12 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('address', models.CharField(max_length=300)),
                ('zip_code', models.IntegerField()),
            ],
        ),
    ]
