# Generated by Django 3.2.2 on 2021-05-12 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourapp', '0002_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='address',
            field=models.CharField(max_length=400),
        ),
    ]
