# Generated by Django 3.2.2 on 2021-05-12 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ourapp', '0003_alter_school_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='School',
            field=models.ForeignKey(default='New School', on_delete=django.db.models.deletion.CASCADE, to='ourapp.school'),
        ),
    ]
